version: 0.0
os: linux

files:
  - source: .
    destination: /home/ec2-user/flask-app

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      runas: ec2-user

  AfterInstall:
    - location: scripts/start_app.sh
      runas: ec2-user
